### ISSUE TITLE
Weird UI issue

### ISSUE THREAD

**Issue by isaackhlam** [CUHK-CIBAY/beaconnect#150]
Not priority, just happen in minority browser lol
Top is Firefox, Bottom is Konqueror by KDE 
User-Agent of bottom: (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.13 Chrome/87.0.4280.144 Safari/537.36)
Actually I think no body use this browser...
![bug](https://github.com/CUHK-CIBAY/beaconnect/assets/97761927/a9733d52-9e91-4f7b-976e-40d592d70dca)

**Comment by AnsonCheng03** [comment]
It might be a problem related to the aspect-ratio CSS property. 
I could not find the docs on css of konqueror browser, and this property is widely supported.

https://caniuse.com/mdn-css_properties_aspect-ratio

**Comment by isaackhlam** [comment]
Nevermind, I think no one use this
